### ISSUE TITLE
GS magnitude is G band not V band

### ISSUE THREAD

**Issue by sylacour** [f4hzg/p2Gravity#1]
V band is almost never used anymore. It is the G band which is asked in the field "GS magnitude". Also, the default values (in case it cannot find a magnitude) should not be zero.

**Comment by f4hzg** [comment]
The new version now uses the Gband instead of V band. It also throws an error instead of using default values when not available in Simbad. If the values cannot be retrieved, you will need to specify them in the yml instead. The examples have been updated accordingly.
