### ISSUE TITLE
HD 25535

### ISSUE THREAD

**Issue by sylacour** [f4hzg/p2Gravity#2]
I have an issue with HD 25535. There are no V of G value in Simbad.
So it made the OB, but it did put zero in the magnitude.
I think it is better if the code does not make the OB and make an error, instead of this. Otherwise, we can think the OB is good, but in fact it would not work at the telescope.

**Comment by f4hzg** [comment]
An error is indeed the expected behaviour, so that's a bug. I've updated the code. Can you let me know if it works better?

**Comment by sylacour** [comment]
It works now! ==>

[ERROR] G band magnitude not found on Simbad for target HD 25535. Please specify a G band mag using 'g_mag: xx' in the yml. See the examples.'

**Comment by sylacour** [comment]
So I think we can close the issue...
